name: PR Guard

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source:
    runs-on: ubuntu-latest

    steps:
      - name: Validate source branch
        run: |
          echo "Branch origem: ${{ github.head_ref }}"

          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "❌ PR para main só pode vir da branch develop."
            exit 1
          fi

          echo "✅ PR válido"
